select distinct category ,subcategory, product_name from dim_products order by 1,2,3




---to find the min, max and datee fifference of the order date 

select min(order_date) as firstoderdate, max(order_date) as lasttoderdate,DATEDIFF(year,MIN(order_date),max(order_date)) as diff from fact_sales




---to find oldes birth date, younges birth date, present age of old and young
select 

min(birthdate) as startbirthdate,
max(birthdate) as endbirthdate,
datediff(year, min(birthdate),getdate()) as curentage,
datediff(year, max(birthdate),getdate()) as curentageyoung

from dim_customers;

---to find sum of sales amount, find how many items are sold ,avg of price and count of orders


select sum(sales_amount) as totalsales,
sum(quantity) as totalquantity,
avg(price) as avgprice,
count(distinct order_number) as totaloder

from fact_sales


---to find total no of products
select count(product_name) as countofprokey,
count(distinct product_name) as disproductkey
from dim_products

---to find total no of customers
select count(customer_key) as customerkey
from dim_customers

---total no of customers that has placed an order
select count(distinct customer_key) as customerkey
from fact_sales











---generate a report shows all key metrics of the business




select  'Total_sales' as measure_name ,sum(sales_amount) as measured_value from fact_sales
union all
select  'total_quantity' as measure_name ,sum(quantity) as measured_value from fact_sales

union all

select 'ave_price', avg(price) 
from fact_sales

union all

select 'totalno_of_orders', count(distinct order_number) 
from fact_sales

union all

 select 'totalnoof_products',count( product_name) 
from dim_products

union all

select'totalnoof_customers', count(customer_key) as customerkey
from dim_customers







---find total customers by country


select country, count(customer_key) as total_customer from dim_customers
group by country
order by total_customer desc
---find total customers by gender

select gender, count(customer_key) as total_customer from dim_customers
group by gender

--find total sales by category

SELECT 
    p.category,
    SUM(f.sales_amount) AS total_sales
FROM fact_sales f
JOIN dim_products p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_sales DESC





---find total products by categor
select category, count(product_key) as total_product from dim_products
group by category
order by total_product desc

--total sales by year 
SELECT YEAR(order_date) AS sales_year,
    SUM(sales_amount) AS total_sales
FROM fact_sales
GROUP BY YEAR(order_date)
ORDER BY sales_year;



--what is the total revenue generated for eacg category

select p.category, sum(f.sales_amount) as total_revenue  from fact_sales as f 
left join dim_products as p
on p.product_key= f.product_key
group by p.category
order by total_revenue desc

--what is the revenue generated by each customer
select c.customer_key,c.first_name,c.last_name, sum(f.sales_amount) as total_revenue  from fact_sales as f 
left join dim_customers as c 
on f.customer_key = c.customer_key
group by c.customer_key,
c.first_name,
c.last_name

order by total_revenue desc



--what is the distribution of sold items across countries
select count(f.quantity) as total_quantity,c.country from fact_sales as f
left join dim_customers as c
on f.customer_key = c.customer_key
group by country
order by total_quantity desc

--find products that never sold

SELECT p.product_name FROM dim_products p
LEFT JOIN fact_sales f
    ON p.product_key = f.product_key
WHERE f.product_key IS NULL




--which 5 products generate the highest revenue




select top 5 p.product_name,sum(f.sales_amount) as total_sales from fact_sales as f left join dim_products as p
on f.product_key = p.product_key
group by product_name
order by total_sales desc


--what are the 5 worst performing in terms of slaes

select top 5 p.subcategory,sum(f.sales_amount) as total_sales from fact_sales as f left join dim_products as p
on f.product_key = p.product_key
group by p.subcategory
order by total_sales asc


--using window function
select * from(
            select p.product_name,sum(f.sales_amount) as total_sales,ROW_NUMBER() over (order by sum(f.sales_amount) desc) as rank  from fact_sales as f left join dim_products as p
           on f.product_key = p.product_key
            group by product_name)t
where rank<=5


---find the top 10 customer who have genereted the highest revenue

select top 10 c.customer_key,c.first_name,c.last_name, sum(f.sales_amount) as total_revenue  from fact_sales as f 
left join dim_customers as c 
on f.customer_key = c.customer_key
group by c.customer_key,
c.first_name,
c.last_name

order by total_revenue desc



---the 3 customemr with the fewest order placed 

select top 3 c.customer_key,c.first_name,c.last_name, count( distinct order_number) as total_orders  from fact_sales as f 
left join dim_customers as c 
on f.customer_key = c.customer_key
group by c.customer_key,
c.first_name,
c.last_name

order by total_orders asc

--monthly sales trend 
SELECT YEAR(order_date) AS year,MONTH(order_date) AS month,
    SUM(sales_amount) AS total_sales
FROM fact_sales
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY year, month
